### ISSUE TITLE
Load GPU trained model in CPU VM

### ISSUE THREAD

**Issue by louis-li** [MaartenGr/BERTopic#384]
Is there a way to load GPU trained model in CPU VM? I'm getting this error: 

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

I tried to use torch.save to save the entire model and loaded it using torch.load with map_location but still got the same result. 

Is there a way to load this model in CPU VM?

**Comment by MaartenGr** [comment]
Yes, I think you can circumvent this issue by not saving the embedding model when you save the BERTopic instance. To skip the embedding model, use: 

`topic_model.save("my_bertopic_model", save_embedding_model=False)` 

Then, when you again load the model, make sure you pass the embedding model again: 

`BERTopic.load("my_bertopic_model", embedding_model=my_embedding_model)`

**Comment by louis-li** [comment]
Thanks @MaartenGr . Will you be able to share a sample? I tried to do what you suggested but getting error:

"<class 'numba.np.ufunc.ufuncbuilder.UFuncTargetOptions'> does not support option: 'target_backend'"

I had other error before this and had to upgrade numbe to 0.54.1.

Here is my code:
For saving:

topic_model = BERTopic(embedding_model="all-MiniLM-L6-v2")
topics, prob = topic_model.fit_transform(df['masked_description'], y=df['targets'])
topic_model.save(model_path, save_embedding_model=False)

For loading:

topic_model = BERTopic.load(model.get_model_path(model.name,  _workspace=workspace), embedding_model="all-MiniLM-L6-v2")

Thanks!

**Comment by MaartenGr** [comment]
The following is working for me on a Google Colab instance where I first start with a GPU runtime and train/save the model:

```python
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic 

# Prepare embeddings
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=False)

# Train our topic model using our pre-trained sentence-transformers embeddings
topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs, embeddings)
topic_model.save("model", save_embedding_model=False)
```

Then I switch to a CPU instance and load the model via:

```python
topic_model = BERTopic.load("model")
```

**Comment by MaartenGr** [comment]
You can try to load the model in a GPU environment, delete `topic_model.embedding_model`, and save the model again. That way, you remove anything related to the GPU instance, and hopefully, it will work in a CPU-only environment.

**Comment by paulthemagno** [comment]
Interesting question. Is there a way to do that if you don't have a GPU environment anymore? @MaartenGr I mean, to load the model and do a `del topic_model.embedding_model` you need the GPU 😊

**Comment by MaartenGr** [comment]
The thing is if you trained a BERTopic instance in a GPU instance I would advise using that same instance to delete the embedding model from your saved BERTopic instance. If you, for whatever reason, do not have access anymore to that GPU instance you can always try to load the model in Kaggle or Google Colab. However, I have difficulty imagining a case where you can only access a GPU instance once and then never again.

**Comment by MaartenGr** [comment]
Due to inactivity, this issue will be closed. Let me know if you want to re-open the issue and I'll be glad to help out!
