### ISSUE TITLE
loading gpu pretrained models in cpu

### ISSUE THREAD

**Issue by Ariannaperla** [MaartenGr/BERTopic#403]
Hello Maarten,
currently I can not use GPU but I need to load several gpu pertained models in cpu in order to evaluate them. As suggested by some users I tried 2 or 3 different methods but I keep obtaining the same error:RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
How can I resolve the problem? Do you have any suggestion ?
Thanks in advance

**Comment by MaartenGr** [comment]
You mention that you have tried 2 or 3 different methods, which ones did you try so far? Also, did you look into [this](https://github.com/MaartenGr/BERTopic/issues/384) thread? If you look at the last post it shows a method that has worked for me thus far.

**Comment by MaartenGr** [comment]
Due to inactivity, I will be closing this issue for now. If you are still experiencing this issue, let me know and I'll re-open the issue.
