### ISSUE TITLE
package requirements in BERTopic need update 

### ISSUE THREAD

**Issue by srashtchi** [MaartenGr/BERTopic#755]
Hi Maarten
I think you need couple of update on package requirements in BERTopic: 

1. there is an error [__init__() got an unexpected keyword argument 'cachedir' when importing top2vec](https://stackoverflow.com/questions/73830225/init-got-an-unexpected-keyword-argument-cachedir-when-importing-top2vec) , due to latest versions of hdbscan and joblib packages available on PyPI.
Unfortunately the latest hdbscan release on PyPi is ver. 0.8.28 as of Feb 8, 2022 and still not updated. It still use memory=Memory(cachedir=None, verbose=0)

One possible solution is to force using joblib version before cachedir was removed - ver. 1.1.0 as of Oct 7, 2021. However note my edit below.

2.facing this error :[RuntimeError: CUDA error: no kernel image is available for execution on the device after model.cuda()](https://stackoverflow.com/questions/69968477/runtimeerror-cuda-error-no-kernel-image-is-available-for-execution-on-the-devi)
it seems torch and torchvision should get back to stable version : 
`pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html`

would appreciate your input on these.

**Comment by MaartenGr** [comment]
> there is an error [init() got an unexpected keyword argument 'cachedir' when importing top2vec](https://stackoverflow.com/questions/73830225/init-got-an-unexpected-keyword-argument-cachedir-when-importing-top2vec) , due to latest versions of hdbscan and joblib packages available on PyPI.

This is a known issue in BERTopic and is indeed solved by reverting back to joblib v1.1.0. Based on your post, it seems that you are referring to [this](https://stackoverflow.com/a/73830525) post. You can also use the latest version of joblib and install HDBSCAN from its main branch which allows for using the latest version of joblib. Do note that there are several issues discussing this on the HDBSCAN repo [here](https://github.com/scikit-learn-contrib/hdbscan/issues/562) and [here](https://github.com/scikit-learn-contrib/hdbscan/issues/565) which might be good places for updates regarding this issue at the source. 

Fixing this within BERTopic would mean installing HDBSCAN from its main branch via pypi which is quite tricky and not the most ideal solution as it would be a very temporary fix. For now, it might be best to install HDBSCAN from its main branch. 

> 2.facing this error :[RuntimeError: CUDA error: no kernel image is available for execution on the device after model.cuda()](https://stackoverflow.com/questions/69968477/runtimeerror-cuda-error-no-kernel-image-is-available-for-execution-on-the-devi)
 it seems torch and torchvision should get back to stable version

Could you share how this issue exactly relates to installing BERTopic? This seems specific to certain versions of pytorch and not necessarily the way BERTopic handles those right?

**Comment by srashtchi** [comment]
it resolved for now, but until sept. with only BERTopic installation all was fine. now it requires to change version on joblib. About torch version you are right I investigated that further, it doesn't related to BERTopic requirements, It was about versioning of my Anaconda.
